--QUESTION NO-1
CREATE TABLE EMP1294111 (
EID NUMBER(4),
ENAME VARCHAR2(30),
SALARY NUMBER(10,2),
HIRE_DATE DATE,
ADDRESS VARCHAR2(255),
CONSTRAINT  sh_EMP1294111_pk primary key (EID));



--QUESTION NO-2
ALTER TABLE EMP1294111 
ADD (DEPARTMENT_ID VARCHAR2(5), DEPARTMENT_NAME VARCHAR2(60));



--QUESTION NO-3
INSERT INTO EMP1294111 
(EID, ENAME, SALARY, HIRE_DATE, ADDRESS, DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (&EID, &ENAME, &SALARY, &HIRE_DATE, &ADDRESS, &DEPARTMENT_ID, &DEPARTMENT_NAME);


INSERT INTO EMP1294111 
(EID, ENAME, SALARY, HIRE_DATE, ADDRESS, DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (&EID, &ENAME, &SALARY, &HIRE_DATE, &ADDRESS, &DEPARTMENT_ID, &DEPARTMENT_NAME);

  
  
--QUESTION NO-4
CREATE VIEW EMP411 (ENAME, DEPT_NAME, SALARY) 
  AS (SELECT FIRST_NAME, DEPARTMENT_NAME, SALARY FROM EMPLOYEES 
     JOIN DEPARTMENTS USING (DEPARTMENT_ID)
      WHERE DEPARTMENT_ID = 80);
 
 
      
--QUESTION NO-5
INSERT INTO EMP1294111 (EID, ENAME, SALARY)
 SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.SALARY FROM employees e;



 --QUESTION NO-6
CREATE SEQUENCE EMP1294111
START WITH 1
  INCREMENT BY 10
   MAXVALUE 9999;
 






      